plugins: 
  - babel
env:
  es6: true
  node: true
extends: 
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
parserOptions:
  sourceType: module
parser: babel-eslint
rules:
  no-console: 0
